config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는path





]

pybo/urls.py
from django.urls import path

from . import views
from .views import  base_views,question_views,answer_views

app_name= 'pybo'

urlpatterns =[
    #base_views
    path('', base_views.index, name='index'),
    path('<int:question_id>/',base_views.detail, name='detail'),
    #question views
    path('question/create/' , question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),


    #answer views
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),


]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')

    def __str__(self):
        return self.subject

# author 에 related_name='author_question' 인수 지정
# voter 에  related_name='voter_question' 인수 지정
# 특정 사용자가 작성한 질문을 얻기 some_user.author_question.all()
# 특정 사용자가 추천한 질문을 얻기 some_user.voter_question.all()


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

pybo/forms.py
from django import forms
from pybo.models import Question ,Answer


###https://docs.djangoproject.com/en/4.0/topics/forms/ 장고 폼 설명
class QuestionForm(forms.ModelForm):
    class Meta:
         model = Question  # 사용할 모델
         fields = ['subject','content']  ## QuestionForm 에서 사용할 Question 모델의 속성
         labels = {
           'subject': '제목',
           'content': '내용',
         }

        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}), # 부트스트랩 적용
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
                'content': '답 변 내 용',
                 }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer


##아래 생성뷰
   # answer 모델 직접참조
    # answer = Answer(question=question,content=request.POST.get('content'),
    #                create_date=timezone.now())
    # answer.save()
@login_required(login_url='common:login') #로그인이필요한 함수 ,함수가실행되면 자동으로 로그인화면이동
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)

    else:
        form = AnswerForm()

    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)




@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'수정권한없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date=timezone.now()
            answer.save()

            print('user', answer.author)
            print('answer.id', answer.id)
            print('answer.question.id', answer.question.id)
            print('answer.question', answer.question)
            print('answer.question.subject', answer.question.subject)
            return redirect('pybo:detail', question_id=answer.question.id)

    else:
        form = AnswerForm(instance=answer)

    context = {'answer':answer,'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭 제 권 한 이 없 습 니 다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)


@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user == answer.author:
        messages.error(request, '본인글은 추천 ㄴ')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.shortcuts import render
from .. models import Question
from django.db.models import Q



def index(request):
    indexpage = request.GET.get('page', '1') #페이지
    kw = request.GET.get('kw', '') #검색어
    question_list = Question.objects.order_by('-create_date') #create_date 역순
    if kw:
        question_list=question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(answer__content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()
    indexpaginator = Paginator(question_list,10)
    indexpage_obj = indexpaginator.get_page(indexpage)
    context = {'question_list': indexpage_obj , 'page':indexpage, 'kw':kw}
    return render(request, 'pybo/question_list.html',context)

def detail(request,question_id):
    question = get_object_or_404(Question, pk=question_id)           #404page표시
    #question = Question.objects.get(id=question_id)                  기존방식
    context = {'question':question}
    return render(request, 'pybo/question_detail.html',context)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question


@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':  #3. 아래 질문등록버튼클릭후 들어오면 폼에 입력값을넣고 submit(POST)호출하면 여기로실행
        form = QuestionForm(request.POST) #4. request.POST를 인수로 QuestionForm 을 생성할 경우에는 request.POST에 담긴 subject,
                                           #  content 값이 QuestionForm 의 subject, content 속성에 자동으로 저장되어 객체가 생성.
        if form.is_valid():
            question = form.save(commit=False) #5. 임시 저장 question 객체를 리턴
            question.author = request.user # 로그인사용자 저장
            question.create_date = timezone.now()   ##6. 시간저장 //임시저장안하면 createdate값이없어서 오류발생
            question.save() # 7. 진짜 저장
            print(request.user) #사용자 이름
            return redirect('pybo:index') # 8. 리스트홈페이지 이동

    else:   # 1. 처음 기본 list페이지 질문등록버튼클릭시 default값을 GET방식 호출 기본 폼만 리다이렉됨
        form = QuestionForm() #html페이지  폼 속성값  유지,저장?


    context= {'form':form}
    return render(request, 'pybo/question_form.html',context) # GET , #3번 form.is_valid(): else 인경우


#수정
@login_required(login_url='common:login')
def question_modify(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한없음')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)#기존instance값 보여주지만 리퀘값 덮어쓱시
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)


    else:
        form = QuestionForm(instance=question) #GET요청경우 질문수정화면에 조회된질문의 제목과내용이 반영될 수 있도록 폼생성

    context = {'form':form}
    return render(request,'pybo/question_form.html',context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request,'삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)

    question.delete()
    return redirect('pybo:index')
@login_required(login_url='common:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    print(type(request.user))
    print(type(request.user.username))
    print(type(question.author))
    print(request.user == question.author)
    if request.user == question.author:
        messages.error(request, '본인글은 추천 ㄴ')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답 변 수 정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답 변 내 용</label>
            <textarea class="form-control" name="content" id="content" 11
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}

<!-- message 표 시 //보여질일없음 다만 이상한경로타면보여짐-->
{% if messages %}
<div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
    <strong>{{ message.tags }}</strong>
    <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
</div>
{% endif %}


<p>test zone : {{ request.user }}</p>
<p>test zone : {{ user }}</p>
<p>test zone : {{ user.username }}</p>
<div class="container my-3">




    <!-- 질 문 -->

    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
              <div class="d-flex justify-content-end">

                  {% if question.modify_date %}
                  <div class="badge bg-light text-dark p-2 text-start mx-3">
                      <div class="mb-2">modified at</div>
                      <div>{{ question.modify_date }}</div>
                  </div>
                            {% endif %}

                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }} </div>
                    <div>{{ question.create_date }}</div>
                </div>

              </div>

                <div class="my-3">

                    <a href="javascript:void(0)" data-uri="{% url 'pybo:question_vote' question.id %}"
                       class="recommend btn btn-sm btn-outline-secondary"> 추 천
                        <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
                    </a>

                         {% if request.user == question.author %}
                    <a href="{% url 'pybo:question_modify' question.id %}"
                       class="btn btn-sm btn-outline-secondary">수 정</a>

                    <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                       data-uri="{% url 'pybo:question_delete' question.id %}">삭 제</a>
                    {% endif %}
                </div>

            </div>

        </div>

    <!-- 답 변 -->


   <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}} 개의 답변 </h5>

        {% for ans in question.answer_set.all %}


        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ ans.content }}</div>
                <div class="d-flex justify-content-end">

                    {% if ans.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ ans.modify_date }}</div>
                    </div>
                                {% endif %}


                    <div class="badge bg-light text-dark p-2 text-start">
                        <div class="mb-2">{{ ans.author.username }}</div>
                        <div>{{ ans.create_date }}</div>
                    </div>
                </div>

                <div class="my-3">

                    <a href="javascript:void(0)" data-uri="{% url 'pybo:answer_vote' ans.id %}"
                       class="recommend btn btn-sm btn-outline-secondary"> 추 천
                        <span class="badge rounded-pill bg-success">{{ans.voter.count}}</span>
                        </a>

                    {% if request.user == ans.author %}
                    <a href="{% url 'pybo:answer_modify' ans.id %}"
                       class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#" class="delete btn btn-sm btn-outline-secondary "
                       data-uri="{% url 'pybo:answer_delete' ans.id %}">삭 제</a>

                    {% endif %}
                </div>

            </div>
        </div>
        {% endfor %}

        <!-- 답 변 등 록 -->
        <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
            {% csrf_token %}
            <!-- 오 류 표 시 Start -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                 <div>
                    <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                </div>
            {% endif %}
            {% endfor %}
            </div>
            {% endif %}
        <!-- 오 류 표 시 End -->
             <div class="mb-3">
                 <label for="content" class="form-label">답 변 내 용</label>
                <textarea {% if not user.is_authenticated %}disabled{% endif %}
                          name="content" id="content" class="form-control" rows="10"></textarea>
              </div>

            <input type="submit" value="답 변 등 록" class="btn btn-primary">
         </form>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    const delete_elements = document.getElementsByClassName("delete")
    Array.from(delete_elements).forEach(function(element){
    element.addEventListener('click', function() {
        if(confirm("정말삭제?"))
        {
          location.href = this.dataset.uri;
        };
    });
});
   const recommend_elements = document.getElementsByClassName("recommend")
    Array.from(recommend_elements).forEach(function(element){
    element.addEventListener('click', function() {
        if(confirm("정말추천z123123zz??"))
        {
          location.href = this.dataset.uri;
        };
    });
});

</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질 문 등 록</h5>

    <!--    action태크없으면 현재페이지 호출-->
        <form method="post">
            {% csrf_token %}
        <!-- {{ form.as_p }} forms.py에 정의한 subject, content 속성에 해당하는 HTML 코드를 자동으로 생성
            백엔드 프론트엔드 구분하기 힘들고 디자인불편 안씀-->
<!--            아래 오류표시 -->
            {% if form.errors %}
           <div class="alert alert-danger" role="alert">
               {% for field in form %}
               {% if field.errors %}
               <div>
                   <strong>{{ field.label }}</strong>
                   {{ field.errors }}
               </div>
               {% endif %}
               {% endfor %}
           </div>
            {% endif %}

        <!-- 아래 디자인코드 -->
        <div class="mb-3">
            <label for="subject" class="form-label">제 목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
                        <!-- form.subject.value|default_if_none:'' 오류발생시 기존값 유지-->
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내 용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>

            <button type="submit" class="btn btn-primary">저 장</button>

        </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
       <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질 문 등 록 하 기</a>
        </div>
    <div class="col-6">
      <div class="input-group">
           <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
               <button class="btn btn-outline-secondary" type="button" id="btn_search">찾 기</button>
            </div>
      </div>
    </div>
    </div>



     <table class="table">
         <thead>
         <tr class="text-center table-dark">
             <th>NUM</th>
             <th style="width:50%">제 목</th>
             <th>글 쓴 이</th>
             <th>TIME</th>
         </tr>
         </thead>
         <tbody>
         {% if question_list %}
         {% for qu in question_list  %}
         <tr class="text-center">
              <!-- for문 카운트방법은 다음페이지도 항상 같음-->
              <!--  forloop.counter0 현재인덱스-->
              <!--  <td>{{ forloop.counter }}</td> -->
             <td>
                 <!-- 번 호 = 전 체 건 수 - 시 작 인 덱 스 - 현 재 인 덱 스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
             </td>
<!-- 아래 제목 -->
             <td class="text-start">
                 <a href="{% url 'pybo:detail' qu.id  %}">{{qu.subject}}</a>
<!--             <a href="/pybo/{{qu.id}}">{{qu.subject}}</a> -->
<!--                 위는 별칭사용 기본방식-->
<!--                 아래는 파라미터 2개이상-->
<!--             <a href="{# url 'pybo:detail' question_id=qu.id page=2 #}">{{qu.subject}}</a>-->
<!-- 아래 제목옆 답변 갯수 -->
                 {% if qu.answer_set.count > 0 %}
                 <span class="text-danger small mx-2">{{qu.answer_set.count}}</span>
                 {% endif %}
             </td>
             <td>{{ qu.author.username }}</td>
             <td>{{ qu.create_date }}</td>
         </tr>
                {% endfor %}
                 {% else %}
         <tr>
             <td colspan="4">no question</td>
         </tr>
                {% endif %}
         </tbody>
     </table>

<!-- 페 이 징 처 리 시 작 -->
    <ul class="pagination justify-content-center">
<!-- 이 전 페 이 지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
            href="javascript:void(0)">이 전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이 전</a>
        </li>
        {% endif %}
<!-- 페 이 지 리 스 트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}

<!-- 다 음 페 이 지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number}}"
            href="javascript:void(0)">다 음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다 음</a>
        </li>
        {% endif %}
    </ul>
 <!-- 페 이 징 처 리 끝 -->

</div>

<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
console.log(page_elements);
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        console.log(this.dataset.page);
        document.getElementById('searchForm').submit();
     });
 });

    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;
        document.getElementById('searchForm').submit();
     });

</script>
{% endblock %}