common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는path





]

pybo/urls.py
from django.urls import path

from . import views
from .views import  base_views,question_views,answer_views

app_name= 'pybo'

urlpatterns =[
    #base_views
    path('', base_views.index, name='index'),
    path('<int:question_id>/',base_views.detail, name='detail'),
    #question views
    path('question/create/' , question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),


    #answer views
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),


]

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.shortcuts import render
from .. models import Question
from django.db.models import Q



def index(request):
    indexpage = request.GET.get('page', '1') #페이지
    kw = request.GET.get('kw', '') #검색어
    question_list = Question.objects.order_by('-create_date') #create_date 역순
    if kw:
        question_list=question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(answer__content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()
    indexpaginator = Paginator(question_list,10)
    indexpage_obj = indexpaginator.get_page(indexpage)
    context = {'question_list': indexpage_obj , 'page':indexpage, 'kw':kw}
    return render(request, 'pybo/question_list.html',context)

def detail(request,question_id):
    question = get_object_or_404(Question, pk=question_id)           #404page표시
    #question = Question.objects.get(id=question_id)                  기존방식
    context = {'question':question}
    return render(request, 'pybo/question_detail.html',context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css'%}">
    <!-- https://getbootstrap.com/docs/5.1/components/card/ -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello pybo</title>
</head>
<body>
<!--네비게인션 바-->
    {% include 'navbar.html' %}
<!-- 기 본 템 플 릿 안 에 삽 입 될 내 용 Start -->

    {% block content %}
    {% endblock %}
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자 바 스 크 립 트 Start -->
    {% block script %}
    {% endblock %}
<!-- 자 바 스 크 립 트 End -->
</body>
</html>

templates/form_errors.html
<!-- 필 드 오 류 와 넌 필 드 오 류 를 출 력 한 다. -->

{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
<!--    필드오류-->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}

<!--    넌필드 오류-->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light border-bottom">
    <div class="container-fluid">
         <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
          <button class="navbar-toggler" type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
          </button>
             <div class="collapse navbar-collapse" id="navbarSupportedContent">
                 <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                          {% if user.is_authenticated %}
                          <a class="nav-link" href="{% url 'common:logout' %}">
                              {{user.username}} (로그아웃)
                          </a>
                          {% else %}
                           <a class="nav-link" href="{% url 'common:login' %}">로 그 인</a>
                          {% endif %}
                      </li>
                     <li>
                         {% if not user.is_authenticated %}
                         <a class="nav-link" href="{% url 'common:signup' %}">회 원 가 입</a>
                         {% endif %}
                     </li>
                 </ul>
             </div>
    </div>
</nav>

<!--뷰함수에서 템플릿에 user 객체를 전달하지않더라도 템플릿에서는 django.contrib.auth-->
<!--기능으로 인해 User 객체를 사용할 수 있음-->